<?php

/**
 * @file
 * Install, update and uninstall functions for the Media entity H5P module.
 */

use Drupal\Core\File\Exception\FileException;
use Drupal\Core\File\FileSystemInterface;

/**
 * Implements hook_install().
 */
function media_entity_h5p_install() {
  \Drupal::messenger()->addStatus(__FUNCTION__);
}

/**
 * Implements hook_uninstall().
 */
function media_entity_h5p_uninstall() {
  \Drupal::messenger()->addStatus(__FUNCTION__);
}
